name = "MyOscar"
uuid = "c0c86ff5-60fd-429e-92dd-1bddbb4390ec"
authors = ["LucaRemke <luca.remke@idsr.uni-stuttgart.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
